#!/usr/bin/env bash
# Transfers a file from client to server

if [[ "$#" -ne 4 ]]; then
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
fi

# Assigning the passed arguments to their various positional variable
FILE_PATH=$1
SERVER_IP=$2
USERNAME=$3
SSH_KEY_PATH=$4

# Disable Strict Host Checking option
SCP_OPTION="-o StrictHostKeyChecking=no"

# Transfer file
scp "$SCP_OPTION" -i "$SSH_KEY_PATH" "$FILE_PATH" "$USERNAME"@"$SERVER_IP":~/
