#!/usr/bin/env bash
# Install nginx web server

# update and upgrade the terminal packages
sudo apt-get update && apt-get upgrade

# Installing nginx
sudo apt-get install nginx -y

# Allow listening on port 80
sudo ufw allow 'Nginx HTTP'

sudo echo 'Hello World!' > /var/www/html/index.nginx-debian.html

# Restarting nginx
sudo service nginx restart
