#!/usr/bin/env bash
# Install nginx web server

# update packages
sudo apt-get update -y

# Installing nginx
sudo apt-get install nginx -y

# Allow listening on port 80
sudo ufw allow 'Nginx HTTP'
sudo ufw allow 80

# sudo chown -R "$USER":"$USER" /var/www/html/index.nginx-debian.html
echo 'Hello World!' | sudo tee /var/www/html/index.nginx-debian.html

# Restarting nginx
sudo service nginx restart

curl localhost
