#!/usr/bin/env bash
# bash script that installs a nginx web server

sudo apt update
sudo apt install nginx -y
sudo ufw allow 22
sudo ufw allow 80
sudo ufw --force enable
sudo ufw status
systemctl status nginx
echo 'Hello World!' | sudo tee /var/www/html/index.html > /dev/null
sudo service nginx restart
