#!/usr/bin/env bash
# displays the PID, along with the processes whose name contain the word bash
pid=$(pgrep -f bash)
for pids in $pid; do
	process_name=$(cat /proc/$pid/cmdline | tr '\0' ' ' | sed 's/ $//')
	echo "$pid$process_name"
done
