#!/bin/env bash
# A script that stops 4-to_infinity_and_beyond process
pid=$(pgrep -f "4-to_infinity_and_beyond")

# Check if the process is running
if [ -n "$pid" ]; then
  # Send a SIGTERM signal to gracefully terminate the process
  kill "$pid"
else
  echo ""
fi
