#!/usr/bin/env bash
# Configure ufw so that it blocks incoming traffic, except the following TCP
# ports
sudo apt-get install -y ufw
sudo ufw default deny incoming
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
sudo ufw disable
sudo ufw enable
